AWSTemplateFormatVersion: 2010-09-09
Resources:
  Topic:
    Type: AWS::SNS::Topic
  DevTopic:
    Type: AWS::SNS::Topic
  User:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Ref Policy
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sns:Publish
              - sns:Subscribe
            Resource:
              - !Ref Topic
              - !Ref DevTopic
          - Effect: Allow
            Action:
              - sns:Publish
              - sns:createPlatformEndpoint
            Resource:
              - !Ref ApplicationArn
Parameters:
  ApplicationArn:
    Type: String
Outputs:
  AwsProdTopicArn:
    Value: !Ref Topic
  AwsDevTopicArn:
    Value: !Ref DevTopic
  AwsAccessKeyId:
    Value: !Ref AccessKey
  AwsSecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
