AWSTemplateFormatVersion: 2010-09-09
Resources:
  Topic:
    Type: AWS::SNS::Topic
  User:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Ref Policy
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sns:Publish
            Resource:
              - !Ref Topic
Outputs:
  TopicArn:
    Value: !Ref Topic
  AccessKeyId:
    Value: !Ref AccessKey
  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
